name: nasa_space_apps
description: لا اله الا الله
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_swiper_plus: ^2.0.4
  flutter_screenutil: ^5.9.0
  cloud_firestore: ^4.9.0
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  animated_button: ^0.2.0
  flutter_stripe: ^9.4.0
  shared_preferences: ^2.2.0
  animated_splash_screen: ^1.3.0
  achievement_view: ^1.0.0
  date_picker_timeline: ^1.2.5
  cached_network_image: ^3.3.0
  ticket_widget: ^0.0.1
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.5.0
  flutter_spinkit: ^5.1.0
  provider: ^6.0.5
  lottie: ^2.6.0
  sn_progress_dialog: ^1.1.3
  animated_text_kit: ^4.2.2
  audioplayers: ^5.1.0
  qr_flutter: ^4.1.0
  uuid: ^3.0.7
  getwidget: ^4.0.0
  currency_picker: ^2.0.17
  url_launcher: ^6.1.12
  intl: ^0.18.1
  rive: ^0.11.4
  path: ^1.8.2
  get: ^4.6.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

#flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 16


flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/images/space_ships/
      - assets/images/elevators/
      - assets/json/
      - assets/sounds/
      - assets/images/
      - assets/riveAssets/
      - assets/fonts/
      - assets/fonts/Dosis/

  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis/Dosis-Bold.ttf
        - asset: assets/fonts/Dosis/Dosis-ExtraBold.ttf
        - asset: assets/fonts/Dosis/Dosis-ExtraLight.ttf
        - asset: assets/fonts/Dosis/Dosis-Light.ttf
        - asset: assets/fonts/Dosis/Dosis-Medium.ttf
        - asset: assets/fonts/Dosis/Dosis-Regular.ttf
        - asset: assets/fonts/Dosis/Dosis-SemiBold.ttf
        - asset: assets/fonts/Dosis/Dosis-VariableFont_wght.ttf
          style: normal
          weight: 500
    - family: Monofett
      fonts:
        - asset: assets/fonts/Monofett-Regular.ttf
          style: normal

    - family: Explora
      fonts:
        - asset: assets/fonts/Explora-Regular.ttf
          style: normal

    - family: Limelight
      fonts:
        - asset: assets/fonts/Limelight-Regular.ttf
          style: normal
          weight: 100
    - family: EnglishSC
      fonts:
        - asset: assets/fonts/IMFellEnglishSC-Regular.ttf
          style: normal
          weight: 100

    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Black.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
          style: normal
          weight: 500
